### ISSUE TITLE
Please provide a license (file)

### ISSUE THREAD

**Issue by barrydegraaff** [frsela/jsDAVlib#3]
Please provide a license (file) for this project, suggest GPL or MIT

**Comment by frsela** [comment]
Is Mozilla Public License because the origin of this code (Firefox OS)

/\* This Source Code Form is subject to the terms of the Mozilla Public
- License, v. 2.0. If a copy of the MPL was not distributed with this file,
- You can obtain one at http://mozilla.org/MPL/2.0/. */

Added LICENSE file - https://github.com/frsela/jsDAVlib/commit/c94c224ac08ab69d8d17c7b8223add39e1b4305a
